import { test as base, type Page } from "@playwright/test";

/**
 * Auth helper for Clerk-authenticated E2E tests.
 *
 * Approach: Use Clerk's development-mode test tokens or session cookies.
 * The recommended way is to set the `__session` cookie for Clerk dev mode,
 * or to use Clerk's testing tokens feature.
 *
 * For local E2E runs the simplest approach is:
 * 1. Log in manually once and export cookies via `storageState`.
 * 2. Reuse that storage state across tests.
 *
 * This fixture provides:
 * - `authenticatedPage`: a page with an active Clerk session.
 * - `unauthenticatedPage`: a clean page with no session (default).
 *
 * Set CLERK_E2E_USER_EMAIL and CLERK_E2E_USER_PASSWORD env vars, or
 * drop a `e2e/.auth/user.json` storage state file (generated by the
 * `auth.setup` project).
 */

const STORAGE_STATE_PATH = "e2e/.auth/user.json";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Perform a full Clerk sign-in through the UI. Falls back to this when no
 * saved storage state is available.
 */
export async function clerkSignIn(
  page: Page,
  email: string,
  password: string,
) {
  await page.goto("/");

  // Click "I have an account"
  await page.getByRole("button", { name: "I have an account" }).click();

  // Clerk modal should appear
  const emailInput = page.locator('input[name="identifier"]');
  await emailInput.waitFor({ timeout: 10_000 });
  await emailInput.fill(email);

  // Click the green CONTINUE button below the email field.
  // Clerk social buttons say "Continue with Apple/Google" — exclude those.
  const continueBtn = page.locator(
    'button:visible:text-is("CONTINUE"), button:visible:text-is("Continue")',
  );
  await continueBtn.first().click();

  // Clerk may show email verification code screen instead of password.
  // If so, click "Use another method" and select "Password".
  const useAnotherMethod = page.getByText("Use another method");
  const passwordInput = page.locator('input[name="password"]');

  // Wait for either password input or "Use another method" link
  await Promise.race([
    passwordInput.waitFor({ timeout: 15_000 }),
    useAnotherMethod.waitFor({ timeout: 15_000 }),
  ]);

  if (await useAnotherMethod.isVisible()) {
    await useAnotherMethod.click();
    // Select password option
    const passwordOption = page.getByText("Password");
    await passwordOption.waitFor({ timeout: 5_000 });
    await passwordOption.click();
  }

  await passwordInput.waitFor({ timeout: 10_000 });
  await passwordInput.fill(password);

  // Click continue again for password step
  const continueBtn2 = page.locator(
    'button:visible:text-is("CONTINUE"), button:visible:text-is("Continue")',
  );
  await continueBtn2.first().click();

  // Wait for Clerk to finish processing. The modal shows a spinner,
  // then either redirects or the modal closes.
  // Strategy: wait for either a URL change or the Clerk modal to close.
  try {
    await page.waitForURL(
      (url) => url.pathname !== "/" || url.search.includes("__clerk"),
      { timeout: 20_000 },
    );
  } catch {
    // The page may stay on "/" with the modal closing
  }

  // Wait for Clerk spinner to finish
  await page.waitForTimeout(3_000);

  // Navigate to a protected page to verify session is active
  const response = await page.goto("/learn", { timeout: 15_000 });
  const status = response?.status() ?? 0;

  // If we get redirected back to sign-in, the session didn't take.
  // In that case, wait a bit more and retry.
  if (status === 401 || status === 307 || status === 302) {
    await page.waitForTimeout(3_000);
    await page.goto("/learn", { timeout: 15_000 });
  }
}

// ---------------------------------------------------------------------------
// Custom test fixture
// ---------------------------------------------------------------------------

type AuthFixtures = {
  authenticatedPage: Page;
};

export const test = base.extend<AuthFixtures>({
  authenticatedPage: async ({ browser }, use) => {
    // Try loading saved storage state; fall back to fresh login.
    let context;
    try {
      context = await browser.newContext({ storageState: STORAGE_STATE_PATH });
    } catch {
      // No saved state — do a fresh login.
      context = await browser.newContext();
      const page = await context.newPage();

      const email = process.env.CLERK_E2E_USER_EMAIL;
      const password = process.env.CLERK_E2E_USER_PASSWORD;

      if (!email || !password) {
        throw new Error(
          "No storage state file and no CLERK_E2E_USER_EMAIL / CLERK_E2E_USER_PASSWORD env vars set. " +
            "Run `npx playwright test --project=auth-setup` first, or set the env vars.",
        );
      }

      await clerkSignIn(page, email, password);
      await context.storageState({ path: STORAGE_STATE_PATH });
      await page.close();
    }

    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

export { expect } from "@playwright/test";
